# Auto generated by PSDB due to incorrect execution
# Read the Docs on how to properly use PSDB
import pythonsimpledatabase, time
pythonsimpledatabase.settings(True, True, True, True)
pythonsimpledatabase.start()
